import Anthropic from "@anthropic-ai/sdk";
import { NextRequest, NextResponse } from "next/server";

const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

export async function POST(req: NextRequest) {
  try {
    const { businessName, domain, industry, province, employees, itSetup, concerns } = await req.json();

    if (!businessName || !industry || !employees) {
      return NextResponse.json({ error: "Missing required fields" }, { status: 400 });
    }

    const concernsList = concerns?.length ? concerns.join(", ") : "general security posture";
    const domainNote = domain ? `Website/Domain: ${domain}` : "No domain provided";
    const today = new Date().toLocaleDateString("en-CA", { year: "numeric", month: "long", day: "numeric" });

    const prompt = `You are a senior cybersecurity consultant specializing in Canadian SMB security and PIPEDA compliance. Generate a comprehensive cybersecurity risk assessment report for the business below. Write in plain English — no jargon. Be specific and actionable.

Today's date is ${today}. Use this exact date if you reference a date anywhere in the report.

BUSINESS INFORMATION:
- Business Name: ${businessName}
- ${domainNote}
- Industry: ${industry}
- Province: ${province}
- Employees: ${employees}
- Current IT Setup: ${itSetup || "Not specified"}
- Primary Security Concerns: ${concernsList}

IMPORTANT: Do NOT include a report title, header block, or metadata section (no "Prepared for:", "Report Date:", etc.). The UI already displays the business name and date. Start your response IMMEDIATELY with the first ## heading below.

Generate the report using EXACTLY this structure:

## Overall Security Risk Score: [X]/100

[2–3 plain-English sentences explaining what this score means for this specific business. Be honest — don't sugarcoat. Mention their industry-specific exposure.]

## Risk Category Scorecard

| Category | Score | Risk Level |
|---|---|---|
| Email Security | X/20 | Critical / High / Moderate / Low |
| PIPEDA Compliance | X/20 | Critical / High / Moderate / Low |
| Data Protection | X/20 | Critical / High / Moderate / Low |
| Network & Endpoint | X/15 | Critical / High / Moderate / Low |
| Access Control | X/15 | Critical / High / Moderate / Low |
| Staff Awareness | X/10 | Critical / High / Moderate / Low |

## Your Industry Risk Profile

[2–3 sentences about the specific cybersecurity risks faced by ${industry} businesses in ${province}. Mention PIPEDA obligations relevant to this industry. Reference specific data types they handle — e.g., patient records for dental, client privilege for legal, SINs for accounting.]

## Top 5 Security Risks

### Risk 1: [Name — most critical risk for this industry]
**Severity:** Critical / High / Moderate
[2–3 sentences: what it is, how it specifically affects ${industry} businesses, one real-world example or stat]

### Risk 2: [Name]
**Severity:** Critical / High / Moderate
[2–3 sentences]

### Risk 3: [Name]
**Severity:** High / Moderate
[2 sentences]

### Risk 4: [Name]
**Severity:** High / Moderate
[2 sentences]

### Risk 5: [Name]
**Severity:** Moderate
[2 sentences]

## PIPEDA Compliance Gap Analysis

[Specific to ${industry} in ${province}. List 3–4 compliance gaps that are common and likely relevant to this business. For each: name the gap, why it's a gap under PIPEDA, and what a breach of it could cost.]

## Priority Action Plan

### Do This Week — Critical
1. [Specific action] — Cost: $0 / Time: [X hours or minutes]
2. [Specific action] — Cost: $0 / Time: [X]
3. [Specific action] — Cost: $0–$X / Time: [X]

### Do This Month — High Priority
1. [Specific action] — Cost: [$X/month or one-time] / Time: [X hours]
2. [Specific action] — Cost: [$X] / Time: [X hours]
3. [Specific action] — Cost: [$X] / Time: [X hours]

### Do This Quarter — Important
1. [Specific action] — Cost: [$X] / Time: [X hours]
2. [Specific action] — Cost: [$X] / Time: [X hours]

## Your Next Step

This report is a starting point — an automated assessment based on your business profile. It does not include live scans of your actual systems, email configuration testing, or dark web monitoring for your specific domain.

Deep Technologies Inc. offers a professional AI-Powered Security Assessment for $1,997 CAD that includes: live email security testing (SPF/DKIM/DMARC), dark web credential scan for your domain, PIPEDA compliance review, network exposure analysis, and a 60-minute walkthrough call — all delivered within 48 hours, in plain English, with a prioritized fix list.

Book at deeptechnologies.ca or call 778-689-0690.

---
*Generated by CyberAudit AI · Powered by Deep Technologies Inc. · deeptechnologies.ca*
*This automated report is for informational purposes. It does not constitute a professional security audit.*`;

    const message = await client.messages.create({
      model: "claude-sonnet-4-6",
      max_tokens: 2048,
      messages: [{ role: "user", content: prompt }],
    });

    const text = message.content[0].type === "text" ? message.content[0].text : "";
    return NextResponse.json({ report: text });
  } catch (err) {
    console.error("Generate error:", err);
    return NextResponse.json({ error: "Failed to generate report" }, { status: 500 });
  }
}
